version: "3.8"

services:
  snx-checkpoint-vpn:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: snx-checkpoint-vpn:latest
    env_file: ./.env
    cap_add:
      - ALL
    tty: true
    volumes:
      - /lib/modules:/lib/modules
      # - ${LOCAL_CERTIFICATE_PATH}:/certificate.p12
    ports:
      - 127.0.0.1:34555:1080
